version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: password_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qH6~*8tq&
    ports:
      - "5432:5432"
    volumes:
      - ./dump_file.sql:/docker-entrypoint-initdb.d/dump_file.sql

  web:
    build:
      context: .
    environment:
      DATABASE_URL: postgresql://postgres:qH6~*8tq&@database/password_manager
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - .:/app